apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a1o2b5tby-python 
  janus-idp.io/tekton: a1o2b5tby-python
  backstage.io/kubernetes-id: a1o2b5tby-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a1o2b5tby-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  